sudo: true

language:
  - "node_js"

node_js:
  - "7.5"

branches:
  only:
    - master
    - 2.x
    - /^greenkeeper/.*$/

before_install:
  - npm install
  - npm install typings -g

addons:
  sauce_connect: true

script:
  - "typings install"
  - "npm run test:ci"