language:
  - "node_js"

node_js:
  - "node"

branches:
  only:
    - master
    - /^greenkeeper/.*$/


addons:
  sauce_connect: true

before_install:
  - npm i -g npm5
  - npm5 i -g greenkeeper-lockfile

install: npm5 install

before_script: greenkeeper-lockfile-update

script:
  - npm5 i -g typings
  - typings install
  - npm5 run test:ci

after_script: greenkeeper-lockfile-upload

after_success:
  - bash ./deploy-docs.sh

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: "A1n8ycSyggWJGeIBSUtlaS6JVcW63AWn6tw9EprzWHeWSvhFRaQ546pmZtObmf03+bTu2KAQFYLoJZHa+FPzxa4+qpOfsMOm30rikWZFQame1MTGMZs0e7NSdDmt4fT4bSI8HOJbut4ODtO7/ynmS3UUyjgp1WpanC7UtMITxfzj0qbxKxxBdDRfZYwp+rlfhvuzuYCxDadzLFyMVJbTD+aTeialH/AQll9LNjxRU15TYLvgqT3mQJ4MEfwSiHVQV4M/ldoEKvHvVRO/ZPXbXUU7rIalGKNklhiMI/N5Cfj5kASGtKlaplbWOkV62Ixa9T/oYpjRmwn4QULv9iICvQs2SlIzBLL7DaRxU/jXf/Sb59CRSOfb5sUt49LTQWTQTwoqDxtvGibjlSrTCwtkoindrbbFsidfbnd99EW5SNecj0QiZjYYd5F7Zv+0rbnr6n6hP40kt/C6HuMdx3Sx0GiMorGD1e/12oI+Yw+c4yAIE89CdCtv7gSlTNiysnNfKRoGYGJGwKdLh9IqMrBSgU+PUJbEoiSmjCHvLEtuIQQaAKMKhJfxMeQmIXhn+Dn76gB1vanAdS/6MZTcKS9hDX41JT9AUaMYGhoWDAB4FFdbIZM9R2Ko2KtZGoB03BIJh8wyPI8uk7iae63Gvq0csJkf5d+U6qxuO0js3DDr3vU="
